/* ─── BRAND DATABASE ─── */
export const BRANDS = [
  {
    name: "Gucci", domanda: 5, velocita: "1-3 giorni", margine: 95,
    note: "Brand più venduto in Italia nel segmento lusso.",
    source: "Privati, Vintage shops", prezzo: "60-400€",
    cosaMeglio: ["Cinture con logo GG", "Borse Dionysus e Marmont", "Sciarpe e foulard", "T-shirt con stampa logo vintage"],
    cosaEvitare: ["Falsi (controlla cuciture, serial number, polvere bag)", "Articoli troppo consumati", "Accessori senza box/dustbag perdono valore"],
    prezzoVendita: "100-600€",
    taglieTop: ["Unica (accessori)", "S-M (abbigliamento)"],
    stagione: "Tutto l'anno, picco a Natale e San Valentino",
    consiglio: "Investi su accessori: cinture e borse hanno margini altissimi e si vendono in 24h. Sempre chiedere foto del serial number prima di comprare.",
    difficolta: "Alta — servono capitali e occhio per i falsi",
  },
  {
    name: "Fendi", domanda: 5, velocita: "3-7 giorni", margine: 95,
    note: "Margini altissimi su borse e accessori.",
    source: "Privati, Aste", prezzo: "50-300€",
    cosaMeglio: ["Borse Baguette e Peekaboo", "Portafogli e cinture", "Foulard con logo FF"],
    cosaEvitare: ["Abbigliamento basic senza logo riconoscibile", "Pezzi troppo datati anni 2000"],
    prezzoVendita: "120-500€",
    taglieTop: ["Unica (accessori)"],
    stagione: "Tutto l'anno",
    consiglio: "La Baguette è tornata di moda grazie a Sex and the City. I modelli vintage anni 90-2000 valgono tantissimo. Cerca nelle aste online.",
    difficolta: "Alta — capitali importanti necessari",
  },
  {
    name: "Stone Island", domanda: 5, velocita: "1-3 giorni", margine: 92,
    note: "Patch originale = vendita garantita.",
    source: "Privati, Vinted", prezzo: "40-150€",
    cosaMeglio: ["Felpe con patch sul braccio", "Giubbotti leggeri", "Pantaloni cargo", "Maglie a maniche lunghe"],
    cosaEvitare: ["FALSI — il mercato è pieno. Controlla: cerchigramma sulla patch, QR code, etichetta interna", "Pezzi senza patch (valgono molto meno)"],
    prezzoVendita: "80-300€",
    taglieTop: ["M", "L", "XL"],
    stagione: "Autunno-Inverno per giubbotti, tutto l'anno per felpe",
    consiglio: "Il brand più sicuro per il resell in Italia. Se la patch è originale, vendi sempre. Compra da privati che non sanno il valore. Foto della patch = must nell'annuncio.",
    difficolta: "Media — i falsi sono il rischio principale",
  },
  {
    name: "Ralph Lauren", domanda: 5, velocita: "1-3 giorni", margine: 90,
    note: "Polo e felpe reggono il prezzo anche molto usati.",
    source: "Mercatini, Thrift shops", prezzo: "20-60€",
    cosaMeglio: ["Polo con logo grande (Big Pony)", "Felpe con zip e logo", "Camicie Oxford button-down", "Maglioni in cotone/lana con logo"],
    cosaEvitare: ["Polo con logo piccolo (margine basso)", "Taglie troppo grandi (XXL+) meno richieste"],
    prezzoVendita: "35-100€",
    taglieTop: ["M", "L"],
    stagione: "Tutto l'anno, polo in primavera-estate",
    consiglio: "Cerca nei mercatini dell'usato — si trova a 5-10€. Le polo Big Pony si vendono a 30-40€. I maglioni invernali con logo cavallo a 25-50€. Facile da trovare, facile da vendere.",
    difficolta: "Bassa — perfetto per iniziare",
  },
  {
    name: "Burberry", domanda: 4, velocita: "3-7 giorni", margine: 90,
    note: "Sciarpe e trench iconici. Il vintage nova check è ricercatissimo.",
    source: "Thrift shops, Privati", prezzo: "30-200€",
    cosaMeglio: ["Sciarpe in cashmere con pattern nova check", "Trench classico beige", "Camicie con pattern check", "Borse vintage"],
    cosaEvitare: ["Falsi — Burberry è molto contraffatto", "Pezzi senza etichetta o con etichette sospette"],
    prezzoVendita: "60-400€",
    taglieTop: ["Unica (sciarpe)", "M-L (trench)"],
    stagione: "Autunno-Inverno per sciarpe e trench",
    consiglio: "Le sciarpe in cashmere sono oro puro: le compri a 20-40€ nei mercatini e le rivendi a 60-100€. Il trench Burberry vintage è un pezzo iconico che vale 150-300€.",
    difficolta: "Media — occhio ai falsi",
  },
  {
    name: "The North Face", domanda: 5, velocita: "1-3 giorni", margine: 88,
    note: "Giacche e gilet a prezzi alti. Stagionalità importante.",
    source: "Mercatini, Vinted stessa", prezzo: "25-80€",
    cosaMeglio: ["Piumini Nuptse (il re del resell)", "Gilet imbottiti", "Giacche in Gore-Tex", "Felpe con logo"],
    cosaEvitare: ["T-shirt basic (margine troppo basso)", "Modelli molto vecchi e rovinati"],
    prezzoVendita: "50-180€",
    taglieTop: ["S", "M", "L"],
    stagione: "Settembre-Febbraio — pubblica prima che faccia freddo",
    consiglio: "Il Nuptse è il prodotto più rivenduto su Vinted Italia. Compralo d'estate quando costa meno e vendilo a ottobre. Le taglie S e M donna vanno fortissimo.",
    difficolta: "Bassa — facile trovare e vendere",
  },
  {
    name: "Nike", domanda: 5, velocita: "1-3 giorni", margine: 85,
    note: "Felpe e tute spariscono in 1-3 giorni.",
    source: "Primark, Mercatini, FB Marketplace", prezzo: "15-45€",
    cosaMeglio: ["Felpe con swoosh centrale", "Tute Tech Fleece", "Giacche a vento vintage", "Air Force 1 e Dunk"],
    cosaEvitare: ["T-shirt basic bianche/nere (troppa concorrenza)", "Scarpe usate molto consumate"],
    prezzoVendita: "30-90€",
    taglieTop: ["M", "L"],
    stagione: "Tutto l'anno, felpe e tute in autunno-inverno",
    consiglio: "Nike è il brand più facile per iniziare. Le felpe vintage con swoosh grande si trovano a 10-15€ e si vendono a 30-40€. Le Tech Fleece sono richiestissime. Foto su sfondo neutro fanno la differenza.",
    difficolta: "Bassissima — il miglior brand per principianti",
  },
  {
    name: "Carhartt", domanda: 4, velocita: "3-7 giorni", margine: 85,
    note: "Nicchia workwear in forte crescita.",
    source: "Mercatini, Import USA", prezzo: "20-50€",
    cosaMeglio: ["Giacche Detroit", "Felpe con logo", "Beanie (cappellini invernali)", "T-shirt con tasca"],
    cosaEvitare: ["Carhartt WIP e Carhartt originale sono diversi — il WIP vale di più nel resell", "Pezzi troppo rovinati dal lavoro"],
    prezzoVendita: "40-120€",
    taglieTop: ["M", "L", "XL"],
    stagione: "Autunno-Inverno per giacche, tutto l'anno per beanie",
    consiglio: "Carhartt WIP è la linea fashion che vale di più. La giacca Detroit vintage è un pezzo cult. Cerca nei mercatini americani online — i prezzi sono più bassi che in Italia.",
    difficolta: "Media — difficile da trovare a poco",
  },
  {
    name: "Adidas", domanda: 5, velocita: "1-3 giorni", margine: 80,
    note: "Trefoil e 3 stripes sempre richiesti.",
    source: "Mercatini, Outlet", prezzo: "12-35€",
    cosaMeglio: ["Felpe con logo Trefoil vintage", "Tute con 3 stripes", "Giacche Firebird", "Samba e Gazelle (scarpe)"],
    cosaEvitare: ["Articoli senza logo visibile", "Scarpe molto usate (suola consumata)"],
    prezzoVendita: "25-70€",
    taglieTop: ["S", "M", "L"],
    stagione: "Tutto l'anno",
    consiglio: "Il vintage Adidas anni 80-90 vale molto di più del nuovo. Le Samba sono le scarpe più cercate del momento. Le tute con zip e 3 stripes laterali si vendono sempre.",
    difficolta: "Bassa — facile da trovare ovunque",
  },
  {
    name: "New Balance", domanda: 4, velocita: "3-7 giorni", margine: 78,
    note: "Modelli 550 e 530 molto richiesti.",
    source: "Outlet, Saldi online", prezzo: "40-90€",
    cosaMeglio: ["550 (bianche/verdi/blu)", "530 (silver)", "990 Made in USA (fascia alta)", "2002R"],
    cosaEvitare: ["Modelli running vecchi (nessuna domanda)", "Colori troppo particolari"],
    prezzoVendita: "70-150€",
    taglieTop: ["40-44 (uomo)", "36-39 (donna)"],
    stagione: "Tutto l'anno",
    consiglio: "Le 550 sono diventate mainstream grazie a Aimé Leon Dore. Comprale in outlet quando sono in saldo e rivendi al prezzo pieno. I colori neutri (bianco, grigio, verde) si vendono più veloci.",
    difficolta: "Media — margine più basso sulle taglie comuni",
  },
  {
    name: "Levi's", domanda: 4, velocita: "3-7 giorni", margine: 78,
    note: "Jeans 501 e vintage anni 80/90 valgono molto.",
    source: "Thrift shops, Mercatini", prezzo: "10-35€",
    cosaMeglio: ["501 vintage (etichetta rossa piccola)", "Giacche trucker in denim", "Jeans 505 e 550 relaxed", "Modelli Made in USA"],
    cosaEvitare: ["Jeans skinny (fuori moda)", "Modelli recenti da negozio (margine basso)"],
    prezzoVendita: "30-80€",
    taglieTop: ["W28-W32 (più richieste)", "Unica (giacche)"],
    stagione: "Tutto l'anno",
    consiglio: "I 501 vintage con etichetta piccola rossa si trovano nei mercatini a 8-15€ e si vendono a 35-60€. Le giacche trucker oversize vanno fortissimo. Metti sempre le misure esatte in cm.",
    difficolta: "Bassa — si trovano facilmente",
  },
  {
    name: "Tommy Hilfiger", domanda: 4, velocita: "3-7 giorni", margine: 75,
    note: "Buona domanda costante, soprattutto uomo.",
    source: "Outlet, FB Marketplace", prezzo: "15-40€",
    cosaMeglio: ["Felpe con logo grande anni 90", "Polo con bandierina", "Giacche leggere", "Maglioni con logo"],
    cosaEvitare: ["T-shirt basic senza logo (troppa concorrenza)", "Taglie molto grandi"],
    prezzoVendita: "30-70€",
    taglieTop: ["M", "L", "XL"],
    stagione: "Tutto l'anno, maglioni in inverno",
    consiglio: "Il vintage Tommy anni 90 con logo grande è molto più richiesto del nuovo. Cerca su FB Marketplace — molti privati vendono lotti interi a prezzi bassi.",
    difficolta: "Bassa — domanda costante",
  },
  {
    name: "Dickies", domanda: 3, velocita: "1-2 settimane", margine: 72,
    note: "Pantaloni cargo e giacche: domanda alta, reperibili a poco.",
    source: "Outlet, Mercatini", prezzo: "8-25€",
    cosaMeglio: ["Pantaloni 874 Original Fit", "Cargo pants", "Giacche da lavoro", "Camicie a maniche corte"],
    cosaEvitare: ["Taglie troppo grandi o troppo piccole", "Colori insoliti (attieniti a nero, beige, verde)"],
    prezzoVendita: "20-50€",
    taglieTop: ["30-34 (pantaloni)", "M-L (giacche)"],
    stagione: "Tutto l'anno",
    consiglio: "I 874 sono un classico dello streetwear. Si trovano nuovi a 15-20€ in outlet e si vendono a 30-40€ su Vinted. Il nero e il beige sono i colori più richiesti.",
    difficolta: "Bassa — facile e sicuro",
  },
  {
    name: "Zara", domanda: 3, velocita: "3-7 giorni", margine: 70,
    note: "Ottimo rapporto costo/velocità.",
    source: "Zara Outlet, Saldi", prezzo: "8-25€",
    cosaMeglio: ["Cappotti strutturati", "Blazer oversize", "Borse (imitano il lusso)", "Pezzi della collezione limitata"],
    cosaEvitare: ["Basic (t-shirt, canotte)", "Pezzi molto comuni che tutti hanno già"],
    prezzoVendita: "18-50€",
    taglieTop: ["S", "M"],
    stagione: "Segui le collezioni — vendi subito dopo l'uscita",
    consiglio: "Il trucco con Zara è comprare durante i saldi al -70% e rivendere come 'nuovo con etichette'. I cappotti invernali comprati a 20€ in saldo si rivendono a 40-50€. Velocità è tutto.",
    difficolta: "Bassissima — perfetto per volume",
  },
  {
    name: "Mango", domanda: 3, velocita: "1-2 settimane", margine: 60,
    note: "Buona rotazione per donna. Meno margine ma veloce.",
    source: "Outlet, Saldi", prezzo: "5-18€",
    cosaMeglio: ["Cappotti e giacche", "Borse in ecopelle", "Vestiti eleganti", "Blazer"],
    cosaEvitare: ["T-shirt e basic (margine zero)", "Pezzi troppo di tendenza che scadono in fretta"],
    prezzoVendita: "15-40€",
    taglieTop: ["S", "M"],
    stagione: "Autunno-Inverno per cappotti, Primavera per vestiti",
    consiglio: "Mango funziona bene per l'abbigliamento donna. Il margine è più basso ma la rotazione è veloce. Compra in saldo, rivendi come 'nuovo'. Abbinalo a Zara per fare volume.",
    difficolta: "Bassissima",
  },
  {
    name: "H&M", domanda: 2, velocita: "2-4 settimane", margine: 50,
    note: "Conviene solo con prezzi bassissimi e lotti.",
    source: "Saldi, Stock", prezzo: "3-10€",
    cosaMeglio: ["Collezioni premium/Studio", "Collaborazioni designer (H&M x Mugler, ecc.)", "Cappotti invernali", "Pezzi con etichetta ancora attaccata"],
    cosaEvitare: ["Basic e fast fashion comune (nessuno lo vuole)", "Pezzi usati di H&M (valore percepito zero)"],
    prezzoVendita: "10-25€",
    taglieTop: ["S", "M"],
    stagione: "Solo saldi e collaborazioni",
    consiglio: "H&M funziona SOLO se compri a 2-5€ durante i mega saldi e rivendi con etichetta come nuovo. Le collaborazioni con designer (H&M x Versace, ecc.) hanno margini alti. Per il resto, evita.",
    difficolta: "Bassa ma margine minimo",
  },
];

export const TIPS = [
  { num: "01", title: "Arbitraggio tra piattaforme", desc: "Compra su FB Marketplace da privati (prezzi bassi, zero commissioni) e rivendi su Vinted dove il pubblico è più ampio.", icon: "🔄" },
  { num: "02", title: "Foto che vendono", desc: "Sfondo bianco o neutro, luce naturale, mostra etichette. Gli annunci con 4+ foto si vendono il doppio più veloci.", icon: "📸" },
  { num: "03", title: "Il trucco delle misure", desc: "Misure esatte in cm nella descrizione. Riduce i resi e aumenta la fiducia dell'acquirente.", icon: "📏" },
  { num: "04", title: "Lotti strategici", desc: "Raggruppa articoli lenti: '3 maglie M', 'Kit running donna'. Si vendono insieme a prezzo conveniente.", icon: "📦" },
  { num: "05", title: "Stagionalità", desc: "Cappotti in ottobre, costumi a maggio, maglioni a settembre. Stagione giusta = vendita in pochi giorni.", icon: "🗓" },
  { num: "06", title: "Budget fisso e ROI", desc: "Fissa un budget mensile (es. 50€). Reinvesti solo i guadagni. Traccia ogni centesimo.", icon: "💰" },
  { num: "07", title: "Specializzati", desc: "Chi vende 'tutto' scompare. Chi vende solo sportswear vintage costruisce pubblico fedele e prezzi più alti.", icon: "🎯" },
  { num: "08", title: "Prezzo competitivo", desc: "Guarda 5 annunci simili già venduti. Mettiti 10-15% sotto per vendere subito. Velocità > margine.", icon: "⚡" },
  { num: "09", title: "Rilancia ogni 3 giorni", desc: "L'algoritmo di Vinted premia gli annunci aggiornati. Rilancia, modifica prezzo di 0.10€, aggiorna foto.", icon: "🔁" },
  { num: "10", title: "Spedizione veloce", desc: "Spedisci entro 24h. Le review positive sulla velocità attirano più acquirenti.", icon: "🚀" },
];

export const CATEGORIE = ["Abbigliamento", "Scarpe", "Accessori", "Borse", "Altro"];
export const FONTI = ["Primark", "Sinsay", "Zara", "H&M", "FB Marketplace", "Mercatino", "Thrift Shop", "Outlet", "Vinted", "Altro"];
export const TAGLIE = ["XS", "S", "M", "L", "XL", "XXL", "Unica", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45"];
export const CONDIZIONI = ["Nuovo con etichette", "Nuovo senza etichette", "Ottime condizioni", "Buone condizioni", "Discrete condizioni"];
export const GENERI = ["Uomo", "Donna", "Unisex"];
export const PIE_COLORS = ["#d4f55e", "#60a5fa", "#c084fc", "#fb923c", "#f87171"];
