/* ─── BRAND DATABASE ─── */
// difficoltaNum: 1=bassissima, 2=bassa, 3=media, 4=alta (used for score calc)
// rischioFalsi: "basso" | "medio" | "alto"
// controlloFalsi: array of checks
export const BRANDS = [
  {
    name: "Gucci", domanda: 5, velocita: "1-3 giorni", margine: 95, difficoltaNum: 4,
    note: "Brand più venduto in Italia nel segmento lusso.",
    source: "Privati, Vintage shops", prezzo: "60-400€",
    cosaMeglio: ["Cinture con logo GG", "Borse Dionysus e Marmont", "Sciarpe e foulard", "T-shirt con stampa logo vintage"],
    cosaEvitare: ["Falsi (controlla cuciture, serial number, polvere bag)", "Articoli troppo consumati", "Accessori senza box/dustbag perdono valore"],
    prezzoVendita: "100-600€",
    taglieTop: ["Unica (accessori)", "S-M (abbigliamento)"],
    stagione: "Tutto l'anno, picco a Natale e San Valentino",
    consiglio: "Investi su accessori: cinture e borse hanno margini altissimi e si vendono in 24h. Sempre chiedere foto del serial number prima di comprare.",
    difficolta: "Alta — servono capitali e occhio per i falsi",
    rischioFalsi: "alto",
    controlloFalsi: ["Controlla il serial number all'interno (6 cifre + 4 cifre)", "Cuciture dritte e regolari, filo di qualità", "Dustbag e box originali (aumentano il valore)", "La stampa GG deve essere simmetrica e nitida", "Confronta con foto ufficiali dal sito Gucci"],
  },
  {
    name: "Fendi", domanda: 5, velocita: "3-7 giorni", margine: 95, difficoltaNum: 4,
    note: "Margini altissimi su borse e accessori.",
    source: "Privati, Aste", prezzo: "50-300€",
    cosaMeglio: ["Borse Baguette e Peekaboo", "Portafogli e cinture", "Foulard con logo FF"],
    cosaEvitare: ["Abbigliamento basic senza logo riconoscibile", "Pezzi troppo datati anni 2000"],
    prezzoVendita: "120-500€",
    taglieTop: ["Unica (accessori)"],
    stagione: "Tutto l'anno",
    consiglio: "La Baguette è tornata di moda grazie a Sex and the City. I modelli vintage anni 90-2000 valgono tantissimo. Cerca nelle aste online.",
    difficolta: "Alta — capitali importanti necessari",
    rischioFalsi: "alto",
    controlloFalsi: ["Controlla il serial number nella tasca interna", "Il pattern FF deve essere perfettamente allineato alle cuciture", "Hardware metallico pesante e inciso (non stampato)", "Etichetta 'Made in Italy' con font specifico", "Zip YKK o Lampo (mai zip generiche)"],
  },
  {
    name: "Stone Island", domanda: 5, velocita: "1-3 giorni", margine: 92, difficoltaNum: 3,
    note: "Patch originale = vendita garantita.",
    source: "Privati, Vinted", prezzo: "40-150€",
    cosaMeglio: ["Felpe con patch sul braccio", "Giubbotti leggeri", "Pantaloni cargo", "Maglie a maniche lunghe"],
    cosaEvitare: ["FALSI — il mercato è pieno", "Pezzi senza patch (valgono molto meno)"],
    prezzoVendita: "80-300€",
    taglieTop: ["M", "L", "XL"],
    stagione: "Autunno-Inverno per giubbotti, tutto l'anno per felpe",
    consiglio: "Il brand più sicuro per il resell in Italia. Se la patch è originale, vendi sempre. Compra da privati che non sanno il valore. Foto della patch = must nell'annuncio.",
    difficolta: "Media — i falsi sono il rischio principale",
    rischioFalsi: "alto",
    controlloFalsi: ["Cerchigramma sulla patch: deve cambiare colore sotto luce diversa", "QR code sulla patch scannerizzabile", "Etichetta interna con art. number verificabile su StoneIsland.com", "Bottoni con incisione 'Stone Island'", "Cuciture regolari e rifinite, mai fili sciolti"],
  },
  {
    name: "Ralph Lauren", domanda: 5, velocita: "1-3 giorni", margine: 90, difficoltaNum: 2,
    note: "Polo e felpe reggono il prezzo anche molto usati.",
    source: "Mercatini, Thrift shops", prezzo: "20-60€",
    cosaMeglio: ["Polo con logo grande (Big Pony)", "Felpe con zip e logo", "Camicie Oxford button-down", "Maglioni in cotone/lana con logo"],
    cosaEvitare: ["Polo con logo piccolo (margine basso)", "Taglie troppo grandi (XXL+) meno richieste"],
    prezzoVendita: "35-100€",
    taglieTop: ["M", "L"],
    stagione: "Tutto l'anno, polo in primavera-estate",
    consiglio: "Cerca nei mercatini dell'usato — si trova a 5-10€. Le polo Big Pony si vendono a 30-40€. I maglioni invernali con logo cavallo a 25-50€. Facile da trovare, facile da vendere.",
    difficolta: "Bassa — perfetto per iniziare",
    rischioFalsi: "basso",
    controlloFalsi: ["Rischio basso — i falsi sono rari e facili da riconoscere", "Controlla che il cavallino sia ricamato bene (non stampato)", "Etichetta interna con paese di produzione"],
  },
  {
    name: "Burberry", domanda: 4, velocita: "3-7 giorni", margine: 90, difficoltaNum: 3,
    note: "Sciarpe e trench iconici. Il vintage nova check è ricercatissimo.",
    source: "Thrift shops, Privati", prezzo: "30-200€",
    cosaMeglio: ["Sciarpe in cashmere con pattern nova check", "Trench classico beige", "Camicie con pattern check", "Borse vintage"],
    cosaEvitare: ["Falsi — Burberry è molto contraffatto", "Pezzi senza etichetta o con etichette sospette"],
    prezzoVendita: "60-400€",
    taglieTop: ["Unica (sciarpe)", "M-L (trench)"],
    stagione: "Autunno-Inverno per sciarpe e trench",
    consiglio: "Le sciarpe in cashmere sono oro puro: le compri a 20-40€ nei mercatini e le rivendi a 60-100€. Il trench Burberry vintage è un pezzo iconico che vale 150-300€.",
    difficolta: "Media — occhio ai falsi",
    rischioFalsi: "alto",
    controlloFalsi: ["Etichetta: 'Burberry' (nuovi) o 'Burberrys' (vintage pre-1999) — mai entrambi", "Sciarpe: cashmere vero è morbidissimo, le frange sono cucite non incollate", "Pattern nova check: le linee devono essere simmetriche e allineate alle cuciture", "Trench: controlla i bottoni con incisione 'Burberry' e la fodera interna"],
  },
  {
    name: "The North Face", domanda: 5, velocita: "1-3 giorni", margine: 88, difficoltaNum: 2,
    note: "Giacche e gilet a prezzi alti. Stagionalità importante.",
    source: "Mercatini, Vinted stessa", prezzo: "25-80€",
    cosaMeglio: ["Piumini Nuptse (il re del resell)", "Gilet imbottiti", "Giacche in Gore-Tex", "Felpe con logo"],
    cosaEvitare: ["T-shirt basic (margine troppo basso)", "Modelli molto vecchi e rovinati"],
    prezzoVendita: "50-180€",
    taglieTop: ["S", "M", "L"],
    stagione: "Settembre-Febbraio — pubblica prima che faccia freddo",
    consiglio: "Il Nuptse è il prodotto più rivenduto su Vinted Italia. Compralo d'estate quando costa meno e vendilo a ottobre. Le taglie S e M donna vanno fortissimo.",
    difficolta: "Bassa — facile trovare e vendere",
    rischioFalsi: "medio",
    controlloFalsi: ["Controlla la zip YKK (deve avere incisione 'YKK')", "Etichetta olografica sul collo (modelli recenti)", "Il logo ricamato deve essere pulito, senza fili fuori posto", "Verifica il codice stile sull'etichetta interna"],
  },
  {
    name: "Nike", domanda: 5, velocita: "1-3 giorni", margine: 85, difficoltaNum: 1,
    note: "Felpe e tute spariscono in 1-3 giorni.",
    source: "Primark, Mercatini, FB Marketplace", prezzo: "15-45€",
    cosaMeglio: ["Felpe con swoosh centrale", "Tute Tech Fleece", "Giacche a vento vintage", "Air Force 1 e Dunk"],
    cosaEvitare: ["T-shirt basic bianche/nere (troppa concorrenza)", "Scarpe usate molto consumate"],
    prezzoVendita: "30-90€",
    taglieTop: ["M", "L"],
    stagione: "Tutto l'anno, felpe e tute in autunno-inverno",
    consiglio: "Nike è il brand più facile per iniziare. Le felpe vintage con swoosh grande si trovano a 10-15€ e si vendono a 30-40€. Le Tech Fleece sono richiestissime. Foto su sfondo neutro fanno la differenza.",
    difficolta: "Bassissima — il miglior brand per principianti",
    rischioFalsi: "basso",
    controlloFalsi: ["Rischio basso per abbigliamento (più alto per scarpe)", "Scarpe: controlla codice stile sulla linguetta e sulla scatola (devono corrispondere)", "Etichetta interna con codice a barre e taglie multiple"],
  },
  {
    name: "Carhartt", domanda: 4, velocita: "3-7 giorni", margine: 85, difficoltaNum: 3,
    note: "Nicchia workwear in forte crescita.",
    source: "Mercatini, Import USA", prezzo: "20-50€",
    cosaMeglio: ["Giacche Detroit", "Felpe con logo", "Beanie (cappellini invernali)", "T-shirt con tasca"],
    cosaEvitare: ["Carhartt WIP e Carhartt originale sono diversi — il WIP vale di più nel resell", "Pezzi troppo rovinati dal lavoro"],
    prezzoVendita: "40-120€",
    taglieTop: ["M", "L", "XL"],
    stagione: "Autunno-Inverno per giacche, tutto l'anno per beanie",
    consiglio: "Carhartt WIP è la linea fashion che vale di più. La giacca Detroit vintage è un pezzo cult. Cerca nei mercatini americani online — i prezzi sono più bassi che in Italia.",
    difficolta: "Media — difficile da trovare a poco",
    rischioFalsi: "basso",
    controlloFalsi: ["Rischio basso — pochi falsi in circolazione", "Distingui Carhartt (workwear) da Carhartt WIP (fashion) — etichette diverse", "WIP ha etichetta quadrata con logo, Carhartt originale ha etichetta rettangolare"],
  },
  {
    name: "Adidas", domanda: 5, velocita: "1-3 giorni", margine: 80, difficoltaNum: 1,
    note: "Trefoil e 3 stripes sempre richiesti.",
    source: "Mercatini, Outlet", prezzo: "12-35€",
    cosaMeglio: ["Felpe con logo Trefoil vintage", "Tute con 3 stripes", "Giacche Firebird", "Samba e Gazelle (scarpe)"],
    cosaEvitare: ["Articoli senza logo visibile", "Scarpe molto usate (suola consumata)"],
    prezzoVendita: "25-70€",
    taglieTop: ["S", "M", "L"],
    stagione: "Tutto l'anno",
    consiglio: "Il vintage Adidas anni 80-90 vale molto di più del nuovo. Le Samba sono le scarpe più cercate del momento. Le tute con zip e 3 stripes laterali si vendono sempre.",
    difficolta: "Bassa — facile da trovare ovunque",
    rischioFalsi: "basso",
    controlloFalsi: ["Rischio basso per abbigliamento", "Scarpe: controlla il codice articolo sulla linguetta interna", "Il logo Trefoil deve essere ricamato in modo pulito"],
  },
  {
    name: "New Balance", domanda: 4, velocita: "3-7 giorni", margine: 78, difficoltaNum: 3,
    note: "Modelli 550 e 530 molto richiesti.",
    source: "Outlet, Saldi online", prezzo: "40-90€",
    cosaMeglio: ["550 (bianche/verdi/blu)", "530 (silver)", "990 Made in USA (fascia alta)", "2002R"],
    cosaEvitare: ["Modelli running vecchi (nessuna domanda)", "Colori troppo particolari"],
    prezzoVendita: "70-150€",
    taglieTop: ["40-44 (uomo)", "36-39 (donna)"],
    stagione: "Tutto l'anno",
    consiglio: "Le 550 sono diventate mainstream grazie a Aimé Leon Dore. Comprale in outlet quando sono in saldo e rivendi al prezzo pieno. I colori neutri (bianco, grigio, verde) si vendono più veloci.",
    difficolta: "Media — margine più basso sulle taglie comuni",
    rischioFalsi: "medio",
    controlloFalsi: ["Controlla il codice modello sulla linguetta e sulla scatola", "La N laterale deve essere cucita, non incollata", "Modelli Made in USA/UK: verifica il paese sulla linguetta"],
  },
  {
    name: "Levi's", domanda: 4, velocita: "3-7 giorni", margine: 78, difficoltaNum: 2,
    note: "Jeans 501 e vintage anni 80/90 valgono molto.",
    source: "Thrift shops, Mercatini", prezzo: "10-35€",
    cosaMeglio: ["501 vintage (etichetta rossa piccola)", "Giacche trucker in denim", "Jeans 505 e 550 relaxed", "Modelli Made in USA"],
    cosaEvitare: ["Jeans skinny (fuori moda)", "Modelli recenti da negozio (margine basso)"],
    prezzoVendita: "30-80€",
    taglieTop: ["W28-W32 (più richieste)", "Unica (giacche)"],
    stagione: "Tutto l'anno",
    consiglio: "I 501 vintage con etichetta piccola rossa si trovano nei mercatini a 8-15€ e si vendono a 35-60€. Le giacche trucker oversize vanno fortissimo. Metti sempre le misure esatte in cm.",
    difficolta: "Bassa — si trovano facilmente",
    rischioFalsi: "basso",
    controlloFalsi: ["Rischio bassissimo — i falsi Levi's sono rari", "Per il vintage: l'etichetta rossa piccola (con la 'E' minuscola) indica pezzi post-1971", "Controlla le cuciture arancioni a doppio filo (caratteristica Levi's)"],
  },
  {
    name: "Tommy Hilfiger", domanda: 4, velocita: "3-7 giorni", margine: 75, difficoltaNum: 2,
    note: "Buona domanda costante, soprattutto uomo.",
    source: "Outlet, FB Marketplace", prezzo: "15-40€",
    cosaMeglio: ["Felpe con logo grande anni 90", "Polo con bandierina", "Giacche leggere", "Maglioni con logo"],
    cosaEvitare: ["T-shirt basic senza logo (troppa concorrenza)", "Taglie molto grandi"],
    prezzoVendita: "30-70€",
    taglieTop: ["M", "L", "XL"],
    stagione: "Tutto l'anno, maglioni in inverno",
    consiglio: "Il vintage Tommy anni 90 con logo grande è molto più richiesto del nuovo. Cerca su FB Marketplace — molti privati vendono lotti interi a prezzi bassi.",
    difficolta: "Bassa — domanda costante",
    rischioFalsi: "basso",
    controlloFalsi: ["Rischio basso — pochi falsi", "Controlla che la bandierina sia ricamata (non stampata)", "Le etichette interne devono avere codice RN e CA"],
  },
  {
    name: "Dickies", domanda: 3, velocita: "1-2 settimane", margine: 72, difficoltaNum: 2,
    note: "Pantaloni cargo e giacche: domanda alta, reperibili a poco.",
    source: "Outlet, Mercatini", prezzo: "8-25€",
    cosaMeglio: ["Pantaloni 874 Original Fit", "Cargo pants", "Giacche da lavoro", "Camicie a maniche corte"],
    cosaEvitare: ["Taglie troppo grandi o troppo piccole", "Colori insoliti (attieniti a nero, beige, verde)"],
    prezzoVendita: "20-50€",
    taglieTop: ["30-34 (pantaloni)", "M-L (giacche)"],
    stagione: "Tutto l'anno",
    consiglio: "I 874 sono un classico dello streetwear. Si trovano nuovi a 15-20€ in outlet e si vendono a 30-40€ su Vinted. Il nero e il beige sono i colori più richiesti.",
    difficolta: "Bassa — facile e sicuro",
    rischioFalsi: "basso",
    controlloFalsi: ["Rischio bassissimo — nessuno fa falsi di Dickies", "Controlla solo che l'etichetta sia quella ufficiale"],
  },
  {
    name: "Zara", domanda: 3, velocita: "3-7 giorni", margine: 70, difficoltaNum: 1,
    note: "Ottimo rapporto costo/velocità.",
    source: "Zara Outlet, Saldi", prezzo: "8-25€",
    cosaMeglio: ["Cappotti strutturati", "Blazer oversize", "Borse (imitano il lusso)", "Pezzi della collezione limitata"],
    cosaEvitare: ["Basic (t-shirt, canotte)", "Pezzi molto comuni che tutti hanno già"],
    prezzoVendita: "18-50€",
    taglieTop: ["S", "M"],
    stagione: "Segui le collezioni — vendi subito dopo l'uscita",
    consiglio: "Il trucco con Zara è comprare durante i saldi al -70% e rivendere come 'nuovo con etichette'. I cappotti invernali comprati a 20€ in saldo si rivendono a 40-50€. Velocità è tutto.",
    difficolta: "Bassissima — perfetto per volume",
    rischioFalsi: "basso",
    controlloFalsi: ["Nessun rischio — nessuno contraffà Zara"],
  },
  {
    name: "Mango", domanda: 3, velocita: "1-2 settimane", margine: 60, difficoltaNum: 1,
    note: "Buona rotazione per donna. Meno margine ma veloce.",
    source: "Outlet, Saldi", prezzo: "5-18€",
    cosaMeglio: ["Cappotti e giacche", "Borse in ecopelle", "Vestiti eleganti", "Blazer"],
    cosaEvitare: ["T-shirt e basic (margine zero)", "Pezzi troppo di tendenza che scadono in fretta"],
    prezzoVendita: "15-40€",
    taglieTop: ["S", "M"],
    stagione: "Autunno-Inverno per cappotti, Primavera per vestiti",
    consiglio: "Mango funziona bene per l'abbigliamento donna. Il margine è più basso ma la rotazione è veloce. Compra in saldo, rivendi come 'nuovo'. Abbinalo a Zara per fare volume.",
    difficolta: "Bassissima",
    rischioFalsi: "basso",
    controlloFalsi: ["Nessun rischio — nessuno contraffà Mango"],
  },
  {
    name: "H&M", domanda: 2, velocita: "2-4 settimane", margine: 50, difficoltaNum: 1,
    note: "Conviene solo con prezzi bassissimi e lotti.",
    source: "Saldi, Stock", prezzo: "3-10€",
    cosaMeglio: ["Collezioni premium/Studio", "Collaborazioni designer (H&M x Mugler, ecc.)", "Cappotti invernali", "Pezzi con etichetta ancora attaccata"],
    cosaEvitare: ["Basic e fast fashion comune (nessuno lo vuole)", "Pezzi usati di H&M (valore percepito zero)"],
    prezzoVendita: "10-25€",
    taglieTop: ["S", "M"],
    stagione: "Solo saldi e collaborazioni",
    consiglio: "H&M funziona SOLO se compri a 2-5€ durante i mega saldi e rivendi con etichetta come nuovo. Le collaborazioni con designer (H&M x Versace, ecc.) hanno margini alti. Per il resto, evita.",
    difficolta: "Bassa ma margine minimo",
    rischioFalsi: "basso",
    controlloFalsi: ["Nessun rischio — nessuno contraffà H&M"],
  },
];

/* ─── Score calculation ─── */
// 40% margine (0-100 → 0-10) + 30% domanda (1-5 → 2-10) + 20% velocità + 10% facilità
export function calcScore(b) {
  const margineScore = (b.margine / 100) * 10;
  const domandaScore = b.domanda * 2;
  const velMap = { "1-3 giorni": 10, "3-7 giorni": 7, "1-2 settimane": 4, "2-4 settimane": 2 };
  const velScore = velMap[b.velocita] || 5;
  const diffNum = b.difficoltaNum || 2;
  const facilitaScore = ((5 - diffNum) / 4) * 10;
  const raw = margineScore * 0.4 + domandaScore * 0.3 + velScore * 0.2 + facilitaScore * 0.1;
  return Math.min(10, Math.round(raw * 10) / 10);
}

/* ─── GUIDA RESELLER — Percorso completo step-by-step ─── */
export const GUIDA = [
  {
    step: 1,
    title: "Scegli la tua nicchia",
    icon: "🎯",
    desc: "Il primo passo per non perdersi: capire cosa vendere, a chi, e perché specializzarsi fa la differenza. Con dati reali dal mercato Vinted Italia.",
    locked: false,
    sections: [
      {
        id: "mercato-vinted",
        title: "Il mercato Vinted Italia — numeri reali",
        content: [
          "Prima di scegliere una nicchia, devi capire dove ti stai muovendo. Vinted in Italia ha circa 5,8 milioni di visite mensili e oltre 4 milioni di utenti registrati. Tra il 2023 e il 2024 le vendite sulla piattaforma sono cresciute del 61%. Non è un mercatino amatoriale: è un ecosistema enorme con concorrenza reale.",
          "La distribuzione degli annunci è squilibrata: quasi il 50% dei prodotti su Vinted sono nella categoria Donna, circa il 33% nella categoria Bambino, e solo il 10% è Uomo. Questo significa che la categoria donna è la più affollata (alta concorrenza) ma anche quella con più acquirenti. La categoria uomo è meno competitiva ma con un bacino più piccolo.",
          "L'Italia è tradizionalmente un Paese di venditori: ci sono più persone che vendono rispetto a quelle che comprano (al contrario della Francia, che è un hub di acquisti). Questo vuol dire che la concorrenza tra venditori italiani è alta. Non basta mettere un annuncio e aspettare — serve una strategia.",
          "Il guadagno medio di chi rivende in Italia è circa 850€ all'anno secondo l'Osservatorio Second Hand Economy (Bva Doxa/Subito.it). Chi fa numeri più alti è chi si specializza, ha fonti di approvvigionamento costanti e tratta il resell come un'attività vera.",
        ],
      },
      {
        id: "perche-nicchia",
        title: "Perché devi scegliere una nicchia",
        content: [
          "Su Vinted ci sono milioni di annunci. Se vendi \"un po' di tutto\" — una maglia Zara, un paio di Nike, una borsa random — il tuo profilo non ha identità. Nessuno ti segue, nessuno si fida, nessuno ti cerca.",
          "Specializzarsi significa diventare riconoscibile. Se vendi solo giacche outdoor vintage, chi cerca quel tipo di prodotto inizia a seguirti, a tornare, a comprare più volte. Costruisci un pubblico.",
          "In termini pratici, la specializzazione ti dà 3 vantaggi concreti:",
          "1. IMPARI A RICONOSCERE IL VALORE — Dopo 50 giacche The North Face sai in 5 secondi se un pezzo vale o no. Non perdi tempo su prodotti che non conosci. Questo è il tuo vero vantaggio competitivo: la conoscenza di nicchia batte qualsiasi trucco di marketing.",
          "2. COMPRI MEGLIO — Sai esattamente cosa cercare ai mercatini, nelle aste, su FB Marketplace. Non giri a vuoto. Mentre gli altri sfogliano tutto il banco, tu vai dritto sui pezzi giusti.",
          "3. VENDI PIÙ VELOCEMENTE — Un profilo coerente e specializzato attira follower interessati. Più follower = più visibilità nell'algoritmo = vendite più rapide. I profili \"tuttologi\" non costruiscono mai un seguito.",
        ],
      },
      {
        id: "nicchie-vinted",
        title: "Le nicchie che funzionano su Vinted Italia",
        content: [
          "Non tutte le nicchie rendono allo stesso modo. Ecco le principali analizzate con dati reali, pro e contro concreti:",
          "━━━ VINTAGE & SECOND-HAND DI MARCA ━━━\nBrand: Ralph Lauren, Burberry, Lacoste, Tommy Hilfiger, Levi's.\nÈ la nicchia più accessibile e più ampia. I capi di questi brand sono tra i più cercati su Vinted in tutta Europa. Le polo Ralph Lauren e Lacoste, le felpe Tommy Hilfiger, i jeans Levi's 501 sono best-seller costanti.\nBudget iniziale: 20-80€\nMargini: 50-150%\nVelocità: media (1-3 settimane)\nDove trovarli: mercatini, thrift shop, FB Marketplace, Humana\nProblema: serve occhio per separare i pezzi buoni (modelli ricercati, condizioni ottime) da quelli che nessuno vuole. Non tutto il vintage ha valore.",
          "━━━ STREETWEAR ━━━\nBrand: Nike, Adidas, Jordan, Carhartt, The North Face, Stüssy, Champion, Dickies.\nPubblico giovane, altissimo volume di ricerca. Le felpe Nike con logo vintage, le giacche Carhartt, i puffer The North Face si vendono velocemente. Le magliette da calcio vintage sono un trend forte nel 2025-2026. Tag come \"Y2K\", \"retro\", \"vintage aesthetic\" e \"90s streetwear\" attirano la Gen Z che cerca ispirazione da TikTok.\nBudget iniziale: 50-200€\nMargini: 30-100%\nVelocità: alta (3-14 giorni)\nDove trovarli: mercatini, stock all'ingrosso (Vundle, TAGZ, Rivintagekilo), aste online\nProblema: i falsi sono ovunque, soprattutto su Jordan e Nike Dunk. Devi imparare ad autenticare. La concorrenza è alta.",
          "━━━ LUXURY ━━━\nBrand: Louis Vuitton, Gucci, Fendi, Prada, Chanel, Dior, Hermès.\nSecondo il Luxury Trend Report di Vinted, Louis Vuitton è il brand luxury più venduto e anche il più veloce da piazzare. In Italia, Fendi e Gucci dominano. Gli articoli più richiesti: la Louis Vuitton Neverfull MM, la giacca Moncler Maya, borse Gucci Dionysus.\nBudget iniziale: 200-500€ (minimo)\nMargini: 100-400%\nVelocità: variabile (1 giorno - 2 mesi)\nDove trovarli: privati, vintage shop specializzati, aste, Vestiaire Collective (per arbitraggio)\nProblema serio: il rischio falsi è enorme. Se compri un falso e lo rivendi, Vinted ti banna l'account PERMANENTEMENTE. Serve esperienza vera nell'autenticazione. Non è una nicchia da principianti.",
          "━━━ SPORTSWEAR TECNICO & OUTDOOR ━━━\nBrand: Patagonia, Arc'teryx, Salomon, Gore-Tex, pile vintage.\nNicchia meno affollata ma con un pubblico disposto a spendere bene. Le giacche Gore-Tex vintage e i pile Patagonia hanno un seguito fedele. È un settore in crescita grazie al trend \"gorpcore\" (moda outdoor).\nBudget iniziale: 30-150€\nMargini: 60-150%\nVelocità: media-bassa (2-4 settimane)\nDove trovarli: mercatini, Humana, privati che svuotano la cantina\nProblema: mercato più piccolo, vendite meno frequenti, ma quando vendi il margine è alto.",
          "━━━ ABBIGLIAMENTO BAMBINO ━━━\nCategoria bambino = circa 33% di tutti gli annunci su Vinted.\nAltissima rotazione: i genitori comprano e rivendono continuamente perché i bimbi crescono. Giocattoli, vestiti, scarpe per fascia 3-5 anni vanno fortissimo.\nBudget iniziale: 10-50€\nMargini: 20-50%\nVelocità: alta (pochi giorni)\nDove trovarli: ovunque — le famiglie svendono a pochissimo\nProblema: prezzi bassi, serve alto volume per guadagnare cifre interessanti. È più un'attività da cash flow continuo che da margini alti.",
          "━━━ ACCESSORI ━━━\nCinture, sciarpe, borse, portafogli, cappelli, foulard di marca.\nOttimi margini, facili da spedire (piccoli e leggeri), e spesso sottovalutati da chi vende. Gli accessori luxury (cinture Gucci, foulard Hermès, portafogli Prada) hanno margini enormi e un mercato costante.\nBudget iniziale: 30-200€\nMargini: 80-200%\nVelocità: media (1-3 settimane)\nDove trovarli: mercatini, privati, thrift shop\nProblema: per il luxury serve autenticazione. Per il non-luxury, serve volume.",
          "━━━ COSMETICI & BEAUTY (NICCHIA EMERGENTE) ━━━\nProfumi sigillati, creme, trucchi nuovi mai aperti di marchi noti.\nNicchia in crescita su Vinted, ma con regole precise: solo prodotti nuovi e sigillati, mai aperti o usati. La data di scadenza deve essere visibile.\nBudget iniziale: 20-100€\nMargini: 30-80%\nVelocità: media\nDove trovarli: outlet, stock, regali mai usati\nProblema: regole Vinted rigide sulla categoria, rischio sospensione se vendi prodotti aperti.",
        ],
      },
      {
        id: "come-scegliere",
        title: "Come scegliere la TUA nicchia — 5 fattori",
        content: [
          "Non esiste la nicchia perfetta in assoluto. Esiste quella giusta per te. Rispondi onestamente a queste 5 domande:",
          "1. COSA CONOSCI GIÀ? — Se sei appassionato di sneaker, parti da lì. Se conosci il vintage perché ci sei cresciuto, quello è il tuo vantaggio. La conoscenza del prodotto è il fattore numero uno: ti fa comprare meglio, vendere meglio, e non prendere fregature. Chi vende senza conoscere il prodotto fa errori costosi.",
          "2. QUANTO PUOI INVESTIRE? — Con 20-50€ puoi iniziare con vintage generico o abbigliamento bambino. Per lo streetwear servono 50-200€. Per il luxury servono almeno 200-500€ solo per partire. Non forzare una nicchia che non puoi permetterti: il capitale bloccato in merce invenduta è il killer numero uno dei reseller principianti.",
          "3. DOVE PUOI TROVARE LA MERCE? — Vivi vicino a mercatini dell'usato? Ci sono thrift shop o Humana nella tua zona? Hai accesso a gruppi FB locali di vendita? La nicchia migliore è quella in cui riesci a trovare merce regolarmente a buon prezzo. Se non hai fonti costanti, non hai un business sostenibile.",
          "4. QUANTO TEMPO HAI? — Vendere luxury richiede più tempo per pezzo (autenticazione, foto dettagliate, trattative lunghe). Il vintage/streetwear generico è più veloce per pezzo ma serve volume. Sii realistico: quante ore a settimana puoi dedicare tra ricerca, foto, spedizioni e messaggi?",
          "5. UOMO, DONNA O BAMBINO? — La categoria donna ha il pubblico più ampio ma la concorrenza più alta. Uomo è meno affollato. Bambino ha rotazione velocissima ma margini bassi. Scegli in base a cosa conosci e cosa trovi più facilmente nella tua zona.",
        ],
      },
      {
        id: "test-nicchia",
        title: "Come testare una nicchia prima di investire",
        content: [
          "Prima di buttare soldi, testa. Ecco il metodo in 3 step da fare in 3 settimane:",
          "STEP A — RICERCA (2-3 ore)\nVai su Vinted, cerca il tipo di prodotto che vuoi vendere. Usa il filtro 'articoli venduti' e analizza: a che prezzo si vendono? In quanto tempo? Ci sono tanti annunci attivi simili o pochi? Se ci sono migliaia di annunci dello stesso prodotto e pochi venduti, quella nicchia è satura. Se ci sono pochi annunci ma venduti velocemente, c'è spazio. Guarda anche i profili dei venditori migliori: cosa fanno bene? Come sono le loro foto? Come scrivono le descrizioni?",
          "STEP B — TEST CON SOLDI VERI (budget: 30-50€ max)\nCompra 3-5 pezzi che secondo la tua ricerca hanno margine. Mettili in vendita con foto curate e descrizioni complete. Non risparmiare sulla presentazione anche se è solo un test — stai testando la nicchia, non quanto puoi tagliare gli angoli.",
          "STEP C — ANALISI (dopo 2-3 settimane)\nRispondi a queste domande: Quanti pezzi hai venduto su 5? Qual è il margine netto (vendita - acquisto - spedizione)? Quanto tempo hai speso in totale (ore)? Dividi il guadagno per le ore: è un ritorno decente? Se su 5 pezzi ne hai venduti 3+ con margine positivo, la nicchia funziona. Se dopo 3 settimane non hai venduto nulla nonostante foto e prezzi competitivi, la nicchia non fa per te.",
          "Regola d'oro: non innamorarti di una nicchia prima di averla testata con soldi veri. Il mercato decide, non il tuo entusiasmo. I dati battono le sensazioni.",
        ],
      },
      {
        id: "stagionalita",
        title: "La stagionalità — quando vendere cosa",
        content: [
          "Su Vinted la stagionalità conta tantissimo. Vendere cappotti a luglio è come vendere gelati a gennaio. Ecco il calendario reale:",
          "GENNAIO-FEBBRAIO — Saldi invernali. La gente compra meno second-hand perché trova sconti nei negozi. Buon momento per fare scorta di merce invernale a prezzi bassissimi (mercatini, privati che svuotano). Vendi: strati intermedi, felpe, maglieria.",
          "MARZO-APRILE — Cambio stagione. Si svuotano gli armadi invernali, si cerca il guardaroba primaverile. Vendi: giacche leggere, camicie, jeans, sneaker. Compra: giacche pesanti e cappotti (la gente li svende).",
          "MAGGIO-GIUGNO — Pre-estate. Altissima domanda per costumi, shorts, t-shirt, sandali, vestiti leggeri, occhiali da sole. È uno dei periodi migliori per vendere. I costumi nuovi con etichetta si vendono in ore.",
          "LUGLIO-AGOSTO — Rallentamento. La gente è in vacanza, le vendite calano. Buon momento per accumulare stock per l'autunno. Compra: pezzi autunnali e invernali in anticipo.",
          "SETTEMBRE-OTTOBRE — Ripartenza fortissima. Tutti cercano giacche, maglioni, cappotti, stivali. È il secondo picco dell'anno. Chi ha fatto scorta in estate vende tutto velocemente.",
          "NOVEMBRE-DICEMBRE — Black Friday e Natale. Domanda alta su regali (accessori luxury, capi di marca nuovi con etichette). I pezzi luxury e gli accessori hanno il picco qui. Attenzione: dopo Natale le vendite crollano per 2-3 settimane.",
          "Consiglio pratico: pubblica i tuoi annunci 4-6 settimane PRIMA della stagione di picco. Se vuoi vendere cappotti in ottobre, mettili online a fine agosto/inizio settembre. L'algoritmo di Vinted premia gli annunci che hanno già views e like quando arriva la domanda.",
        ],
      },
      {
        id: "attenzione-fisco",
        title: "⚠️ Attenzione: il Fisco e la DAC7",
        content: [
          "Questo è un argomento che molti reseller ignorano, e non dovresti. Dal 1° gennaio 2023 è in vigore la direttiva europea DAC7 (recepita in Italia con D.Lgs. n. 32/2023). Le piattaforme come Vinted sono obbligate a segnalare al Fisco i venditori che superano certe soglie.",
          "LE SOGLIE DAC7: Se in un anno superi 30 vendite OPPURE 2.000€ di incasso totale (basta uno dei due), Vinted ti chiede di compilare il formulario DAC7 con: nome, cognome, data di nascita, residenza, codice fiscale. Questi dati vengono trasmessi all'Agenzia delle Entrate. Se non compili il formulario, Vinted ti nasconde gli annunci, blocca il saldo e impedisce i trasferimenti.",
          "LA SEGNALAZIONE NON È UNA TASSA. Superare le soglie DAC7 non significa automaticamente dover pagare tasse. Significa che il Fisco verrà a conoscenza delle tue vendite e potrà verificare se la tua attività è occasionale (nessun obbligo fiscale) o abituale (obbligo di partita IVA).",
          "QUANDO SERVE LA PARTITA IVA? Secondo la Corte di Cassazione (sentenza n. 7552 del 21 marzo 2025), chi fa vendite online con regolarità e continuità può essere considerato imprenditore a fini fiscali, anche senza una struttura organizzata. I criteri chiave sono: frequenza delle vendite, acquisto di merce appositamente per rivendere, promozione attiva, e durata nel tempo.",
          "QUANDO NON SERVE? Se vendi oggetti personali usati, occasionalmente, senza organizzazione e senza scopo di lucro continuativo. In pratica: svuotare l'armadio è ok. Comprare stock per rivenderli regolarmente è attività commerciale.",
          "Vinted ha introdotto la categoria 'Seller Pro' anche in Italia: venditori con partita IVA che devono seguire regole diverse su resi, rimborsi e diritto di recesso (14 giorni). Vinted stessa può chiederti di diventare Pro se rileva segnali di attività professionale (es. molti capi nuovi con cartellino).",
          "CONSIGLIO PRATICO: se il resell diventa un'attività regolare e superi le soglie, consulta un commercialista. Non è un costo, è una protezione. Il regime forfettario in Italia permette di gestire l'attività con costi fiscali contenuti. Non ignorare questo aspetto: le multe per evasione fiscale sono molto più costose della partita IVA.",
        ],
      },
      {
        id: "errori-nicchia",
        title: "I 5 errori letali da non fare",
        content: [
          "ERRORE 1: VENDERE DI TUTTO — Il tuo profilo sembra un mercatino delle pulci digitale. Nessuno ti segue, nessuno si fida, l'algoritmo non sa come categorizzarti. Risultato: visibilità zero.",
          "ERRORE 2: PARTIRE DAL LUXURY SENZA ESPERIENZA — Se non sai autenticare, rischi: comprare falsi → rivenderli → ban permanente da Vinted → perdere tutto il capitale e l'account con le recensioni. Il luxury si affronta dopo mesi su nicchie più sicure. Punto.",
          "ERRORE 3: COPIARE I TIKTOKER — Vedi qualcuno che fa 1000€/mese con le Jordan? Probabilmente ha fonti che tu non hai, mesi di esperienza nell'autenticazione, un profilo con centinaia di recensioni, e un budget iniziale più alto del tuo. Non puoi replicare il suo risultato dal giorno uno. Costruisci il tuo percorso.",
          "ERRORE 4: IGNORARE I NUMERI — \"Mi sembra che vada bene\" non è una strategia. Devi sapere esattamente: quanto hai speso, quanto hai guadagnato, il margine per pezzo, il tempo medio di vendita, il costo delle spedizioni. Senza numeri precisi stai giocando d'azzardo. (Per questo esiste la sezione Inventario di questa app.)",
          "ERRORE 5: CAMBIARE NICCHIA OGNI SETTIMANA — Dai almeno 4-6 settimane e 10-15 pezzi venduti prima di decidere che una nicchia non funziona. Servono tempo, annunci attivi e feedback per capire se c'è potenziale reale. L'impazienza uccide più business della concorrenza.",
        ],
      },
    ],
  },
  {
    step: 2,
    title: "Dove trovare la merce",
    icon: "🔍",
    desc: "Fonti reali, prezzi, vantaggi e svantaggi di ogni canale d'acquisto.",
    locked: true,
    sections: [],
  },
  {
    step: 3,
    title: "Valutare un pezzo",
    icon: "🧠",
    desc: "Come capire in 60 secondi se un articolo vale la pena di essere comprato.",
    locked: true,
    sections: [],
  },
  {
    step: 4,
    title: "Preparare il prodotto",
    icon: "✨",
    desc: "Pulizia, stiratura, presentazione: come trasformare un capo usato in un prodotto appetibile.",
    locked: true,
    sections: [],
  },
  {
    step: 5,
    title: "Fotografare per vendere",
    icon: "📸",
    desc: "Setup, luce, angolazioni, errori da evitare. Le foto vendono più della descrizione.",
    locked: true,
    sections: [],
  },
  {
    step: 6,
    title: "Creare l'annuncio perfetto",
    icon: "📝",
    desc: "Titolo, descrizione, prezzo, categorie, hashtag. Come farsi trovare dall'algoritmo.",
    locked: true,
    sections: [],
  },
  {
    step: 7,
    title: "Gestire gli annunci",
    icon: "🔄",
    desc: "Rilanciare, modificare il prezzo, boost, quando togliere un annuncio.",
    locked: true,
    sections: [],
  },
  {
    step: 8,
    title: "Gestire i compratori",
    icon: "💬",
    desc: "Messaggi, trattative, offerte basse, come rispondere per chiudere la vendita.",
    locked: true,
    sections: [],
  },
  {
    step: 9,
    title: "Spedire",
    icon: "📦",
    desc: "Imballaggio, etichette, tempi, corrieri e come non perdere soldi sulla spedizione.",
    locked: true,
    sections: [],
  },
  {
    step: 10,
    title: "Dopo la vendita",
    icon: "⭐",
    desc: "Recensioni, resi, dispute, e come proteggere il tuo account.",
    locked: true,
    sections: [],
  },
  {
    step: 11,
    title: "Crescere e scalare",
    icon: "📈",
    desc: "Budget, reinvestimento, obiettivi, quando aprire partita IVA, limiti Vinted.",
    locked: true,
    sections: [],
  },
];

export const CATEGORIE = ["Abbigliamento", "Scarpe", "Accessori", "Borse", "Altro"];
export const FONTI = ["Primark", "Sinsay", "Zara", "H&M", "FB Marketplace", "Mercatino", "Thrift Shop", "Outlet", "Vinted", "Altro"];
export const TAGLIE = ["XS", "S", "M", "L", "XL", "XXL", "Unica", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45"];
export const CONDIZIONI = ["Nuovo con etichette", "Nuovo senza etichette", "Ottime condizioni", "Buone condizioni", "Discrete condizioni"];
export const GENERI = ["Uomo", "Donna", "Unisex"];
export const PIE_COLORS = ["#d4f55e", "#60a5fa", "#c084fc", "#fb923c", "#f87171"];
